# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

"""Remove is_active from stories.

Revision ID: 015
Revises: 014
Create Date: 2014-04-09 16:52:36.375926

"""

# revision identifiers, used by Alembic.
revision = '015'
down_revision = '014'


from alembic import op
import sqlalchemy as sa


def upgrade(active_plugins=None, options=None):

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'stories', u'is_active')

    ### end Alembic commands ###


def downgrade(active_plugins=None, options=None):

    ### commands auto generated by Alembic - please adjust! ###

    op.add_column(u'stories',
                  sa.Column('is_active', sa.Boolean(), default=True,
                            server_default="1",
                            nullable=False))

    ### end Alembic commands ###
