# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

"""We need to know who has created a task.

Revision ID: 016
Revises: 015
Create Date: 2014-04-15 17:16:07.368141

"""

# revision identifiers, used by Alembic.
revision = '016'
down_revision = '015'


from alembic import op
import sqlalchemy as sa


def upgrade(active_plugins=None, options=None):

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks',
                  sa.Column('creator_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade(active_plugins=None, options=None):

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'creator_id')
    ### end Alembic commands ###
