# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

"""Add story and tag mapping table.

Revision ID: 023
Revises: 022
Create Date: 2014-08-13 13:47:29.795996

"""

# revision identifiers, used by Alembic.
revision = '023'
down_revision = '022'


from alembic import op
import sqlalchemy as sa

MYSQL_ENGINE = 'InnoDB'
MYSQL_CHARSET = 'utf8'


def upgrade(active_plugins=None, options=None):

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_storytags',
        sa.Column('story_id', sa.Integer(), nullable=True),
        sa.Column('storytag_id', sa.Integer(), nullable=True),
        mysql_engine=MYSQL_ENGINE,
        mysql_charset=MYSQL_CHARSET
    )
    op.drop_constraint('storytags_ibfk_1', 'storytags', type_='foreignkey')
    op.drop_column(u'storytags', u'story_id')
    ### end Alembic commands ###


def downgrade(active_plugins=None, options=None):

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'storytags',
                  sa.Column('story_id', sa.Integer(), nullable=True))
    op.create_foreign_key('storytags_ibfk_1', 'storytags',
                          'stories', ['story_id'], ['id'])
    op.drop_table('story_storytags')
    ### end Alembic commands ###
