- job:
    name: storyboard-tox-sqlite
    parent: openstack-tox
    description: |
      Run tests using sqlite instead of mysql.
    vars:
      tox_envlist: sqlite

- project:
    name: openstack-infra/storyboard
    check:
      jobs:
        - tox-cover:
            timeout: 6000
        - storyboard-tox-sqlite
        - tox-pep8
        - tox-py27:
            timeout: 6000
        - tox-py35:
            timeout: 6000
            nodeset: ubuntu-xenial
    gate:
      jobs:
        - storyboard-tox-sqlite
        - tox-pep8
        - tox-py27:
            timeout: 6000
        - tox-py35:
            timeout: 6000
            nodeset: ubuntu-xenial
    post:
      jobs:
        - publish-openstack-python-branch-tarball
